--- #YAML:1.0
name:               HTML-Perlinfo
version:            1.62
abstract:           ~
author:
    - Mike Accardo (accardo@cpan.com)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/mixedconnections/HTML-Perlinfo.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
